In [1]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#import requests

In [5]:
df = pd.read_csv('DATA_HS_Total_All_Merchandise_Exports_to_World.csv')

In [24]:
df.head()

,Item,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,TOTAL,1148198722191,1287441996730,1056042963028,1278494525839,1482507755226,1545820839892,1578516879950,1621873792910,1503328349746,1451023529686,1546272961061
1,84--NUCLEAR REACTORS; BOILERS; MACHINERY ETC.;...,179294453398,190627440227,153159958043,182902860899,205826159717,215180487807,213440918266,219935033494,206322326264,190729618046,202035662651
2,85--ELECTRIC MACHINERY ETC; SOUND EQUIP; TV EQ...,147811354753,152466732455,124817076765,151776704354,159468543383,162434694242,165818048345,172372237084,170010926769,167127172860,174424000525
3,27--MINERAL FUEL; OIL ETC.; BITUMIN SUBST; MIN...,42247963045,76940267425,55059238358,81692031854,130566667652,137332528657,148902536669,156447655504,104781536243,93792948050,139025423812
4,88--AIRCRAFT; SPACECRAFT; AND PARTS THEREOF,83882874225,84376185197,82977746555,79617922992,87757246448,104440079691,114886824530,125235692852,131661791153,134738835356,131143849163

In [25]:
df[3:].head()

,Item,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
3,27--MINERAL FUEL; OIL ETC.; BITUMIN SUBST; MIN...,42247963045,76940267425,55059238358,81692031854,130566667652,137332528657,148902536669,156447655504,104781536243,93792948050,139025423812
4,88--AIRCRAFT; SPACECRAFT; AND PARTS THEREOF,83882874225,84376185197,82977746555,79617922992,87757246448,104440079691,114886824530,125235692852,131661791153,134738835356,131143849163
5,87--VEHICLES; EXCEPT RAILWAY OR TRAMWAY; AND P...,107212566719,111697565311,73668555474,99148692588,120011780504,133078052912,134090149318,136021619352,127366637466,124565895657,130179115971
6,90--OPTIC; PHOTO ETC; MEDIC OR SURGICAL INSTRM...,65216983434,69381093602,65057411901,73960066842,79383778894,83367062357,84344595248,84976081299,83433294101,82015375908,83637978332
7,39--PLASTICS AND ARTICLES THEREOF,48003056210,51361149796,42854069521,53625263449,58743604827,59006434035,61045249532,63121681924,60347504335,58626886998,61892626784